### ISSUE TITLE
[v0.1.4] Incorrect entry point in package.json

### ISSUE THREAD

**Issue by ThomasHenrissat** [RobertFOConnor/react-native-number-ticker#2]
Hi, thank you for the rapid fix last time!

There is an issue with the `package.json` in the last release.
You seem to have changed the structure of the module by adding a `src` folder, but the entry point in the package as not been updated to match that change.
The `"main"` property still points to `"index.js"` when it should be `"src/index.js"`.

Most likely just a small oversight, but it generates a pretty brutal error ^^

**Comment by RobertFOConnor** [comment]
One step forward and two steps back..
I'll push the fix later today, thanks again.

**Comment by RobertFOConnor** [comment]
Fixed!

**Comment by ThomasHenrissat** [comment]
Ahah it's okay, thank you very much!
