### ISSUE TITLE
width too small

### ISSUE THREAD

**Issue by FraserCampbell1** [RobertFOConnor/react-native-number-ticker#6]
I noticed you are making the width 62% of the textSize. 

![image](https://user-images.githubusercontent.com/53017082/65617230-4c605600-dfb4-11e9-95a7-9622480313c1.png)

This is currently cutting the numbers in my number ticker, is there a reason the width is being cut to 62%?

**Comment by RobertFOConnor** [comment]
Hi Fraser, the reason for this was for optimal display with the font I was using. I understand that when using different fonts this percentage will obviously need to be adjustable using a prop value. This could be something to add in a future version.

**Comment by FraserCampbell1** [comment]
Appreciate the quick response. I thought that was the case! But just wanted to check I hadn't missed anything else. Thanks
